"""tasks

Revision ID: 2f9313691360
Revises: 1cc8be95b28f
Create Date: 2025-03-25 20:05:25.101833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9313691360'
down_revision: Union[str, None] = '3fb13f1760f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('finished_by', sa.String(), nullable=True),
    sa.Column('date_of_start', sa.DateTime(), nullable=False),
    sa.Column('date_of_finish', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['finished_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###